#!/bin/bash
# Mikael Kall
#
# Wifi hacking script 

# Jump to script folder.
SCRIPT_DIR=$(dirname $0)
cd ${SCRIPT_DIR}

# Default settings.
SCRIPT_BASE=$(pwd)

# Load functions library.
if [ -e "./plib.sh" ]; then
    plib="./plib.sh"
else
    plib=$(which plib.sh)
    if [ -z "${plib}" ]; then 
        echo "error plib.sh cannot be found"
        exit 1
    fi
fi

# Load library
. ${plib}

function main()
{
    cleanup

    while :
    do
        print_usage
        color.lightgreen ""
        echo -n "➜ "
        read -n1 opt

        case "${opt}" in

            q|quit)
                echo ""
                exit 0
            ;;

            l|list)
	        list_network $@
   	    ;;

   	    v|view)
	        view_network $@
   	    ;;

   	    d|deauth)
	        deauth_network $@
   	    ;;
   	esac
   done
   exit 0
}

####
## Entry point
####
NAME=$(basename "$0")
if [ "$NAME" == "penetrator" ]; then
    main $@
fi
